service: serverless-graphql-appsync-lda

frameworkVersion: ">=1.21.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-plugin-typescript
  - serverless-appsync-simulator
  - serverless-appsync-plugin
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  appsync-simulator:
    functions:
      graphql:
        handler: handler.graphqlHandler

  accountId: 1234xxxxxxxx # replace this with your accountId
  appSync:
    name: Test
    # name:  # defaults to api
    # apiId # only required for update-appsync
    authenticationType: AMAZON_COGNITO_USER_POOLS # API_KEY is also supported
    userPoolConfig:
      awsRegion: us-east-1 # required # region
      defaultAction: ALLOW
      userPoolId: us-east-1_xxxxxxxxx # replace this with your Cognito User Pool Id
    # region: # defaults to provider region
    mappingTemplatesLocation: mapping-templates
    mappingTemplates:
      - dataSource: Lambda
        type: Mutation
        field: updateUser
        request: "updateUser-request-mapping-template.txt"
        response: "updateUser-response-mapping-template.txt"
      - dataSource: Lambda
        type: Mutation
        field: updateCustomer
        request: "updateCustomer-request-mapping-template.txt"
        response: "updateCustomer-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: users
        request: "users-request-mapping-template.txt"
        response: "users-response-mapping-template.txt"
      - dataSource: Lambda
        type: Query
        field: customers
        request: "customers-request-mapping-template.txt"
        response: "customers-response-mapping-template.txt"
    # schema: # defaults schema.graphql
    serviceRole: "AppSyncServiceRole"
    dataSources:
      - type: AWS_LAMBDA
        name: Lambda
        description: "Lambda DataSource"
        config:
          functionName: myLambda
          lambdaFunctionArn: "arn:aws:lambda:us-east-1:${self:custom.accountId}:function:serverless-graphql-appsync-lda-production-graphql"
          serviceRoleArn: "arn:aws:iam::${self:custom.accountId}:role/Lambda-${self:custom.appSync.serviceRole}"
  serverless-offline:
    port: 4000
  webpackIncludeModules: true

functions:
  myLambda:
    handler: handler.graphqlHandler

resources:
  Resources:
    AppSyncServiceRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: "Lambda-AppSyncServiceRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: "Allow"
              Principal:
                Service:
                  - "appsync.amazonaws.com"
              Action:
                - "sts:AssumeRole"
        Policies:
          - PolicyName: "Lambda-AppSyncServiceRole-Policy"
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: "Allow"
                  Action:
                    - "lambda:invokeFunction"
                  Resource:
                    - "arn:aws:lambda:us-east-1:*:function:serverless-graphql-appsync-lda-production-graphql"
                    - "arn:aws:lambda:us-east-1:*:function:serverless-graphql-appsync-lda-production-graphql:*"
